spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/pass_local?zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: pass_local_user
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false